---
- name: Consultar estado de SSH
  hosts: server1
  gather_facts: true  # Recopila información sobre el sistema
  tasks:
    - name: Obtener estado del servicio SSH
      systemd:
        name: sshd
      register: sshd_status

    - name: Mostrar estado del servicio SSH
      debug:
        var: sshd_status

