Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/bionic64" # Ubuntu 18.04
  
    # Redirección de puertos
    config.vm.network "forwarded_port", guest: 80, host: 8080 # Redirecciona http://localhost:8080/
    config.vm.network "private_network", type: "dhcp" # Red VM asignada con DHCP
  
    # Configuración de recursos para la VM
    config.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 2
    end
  
    # Aprovisionamiento con Ansible
    config.vm.provision "ansible" do |ansible|
        ansible.playbook = "provision.yml"
        ansible.extra_vars = { ansible_python_interpreter: "/usr/bin/python3" }
      end


    # wordpress con Ansible
    config.vm.provision "ansible" do |ansible|
        ansible.playbook = "wordpress.yml"
      end

  end
  